starter_books = [
  { "name": "1984", "author": "George Orwell", "year": 1949, "genre": "Dystopian", "copies": 5},
  { "name": "Pride and Prejudice", "author": "Jane Austen", "year": 1813, "genre": "Romance", "copies": 2},
  { "name": "Moby-Dick", "author": "Herman Melville", "year": 1851, "genre": "Adventure", "copies": 3},
  { "name": "To Kill a Mockingbird", "author": "Harper Lee", "year": 1960, "genre": "Southern Gothic", "copies": 1},
  { "name": "The Hobbit", "author": "J. R. R. Tolkien", "year": 1937, "genre": "Fantasy", "copies": 5},
  { "name": "The Catcher in the Rye", "author": "J. D. Salinger", "year": 1951, "genre": "Coming-of-age", "copies": 4},
  { "name": "The Great Gatsby", "author": "F. Scott Fitzgerald", "year": 1925, "genre": "Tragedy", "copies": 2},
  { "name": "Frankenstein", "author": "Mary Shelley", "year": 1818, "genre": "Gothic science fiction", "copies": 3},
  { "name": "One Hundred Years of Solitude", "author": "Gabriel García Márquez", "year": 1967, "genre": "Magical realism", "copies": 1},
  { "name": "The Name of the Rose", "author": "Umberto Eco", "year": 1980, "genre": "Historical mystery", "copies": 2},
  { "name": "Brave New World", "author": "Aldous Huxley", "year": 1932, "genre": "Dystopian", "copies": 3},
  { "name": "Fahrenheit 451", "author": "Ray Bradbury", "year": 1953, "genre": "Dystopian", "copies": 4},
  { "name": "Animal Farm", "author": "George Orwell", "year": 1945, "genre": "Political satire", "copies": 4},
  { "name": "Lord of the Flies", "author": "William Golding", "year": 1954, "genre": "Allegorical fiction", "copies": 2},
  { "name": "The Handmaid's Tale", "author": "Margaret Atwood", "year": 1985, "genre": "Dystopian", "copies": 2},
  { "name": "The Road", "author": "Cormac McCarthy", "year": 2006, "genre": "Post-apocalyptic", "copies": 2},
  { "name": "A Clockwork Orange", "author": "Anthony Burgess", "year": 1962, "genre": "Dystopian", "copies": 1},
  { "name": "The Giver", "author": "Lois Lowry", "year": 1993, "genre": "Dystopian", "copies": 5},
  { "name": "Never Let Me Go", "author": "Kazuo Ishiguro", "year": 2005, "genre": "Dystopian", "copies": 2},
  { "name": "Station Eleven", "author": "Emily St. John Mandel", "year": 2014, "genre": "Post-apocalyptic", "copies": 3},
  { "name": "Jane Eyre", "author": "Charlotte Brontë", "year": 1847, "genre": "Gothic romance", "copies": 3},
  { "name": "Wuthering Heights", "author": "Emily Brontë", "year": 1847, "genre": "Gothic fiction", "copies": 2},
  { "name": "Emma", "author": "Jane Austen", "year": 1815, "genre": "Romance", "copies": 2},
  { "name": "Sense and Sensibility", "author": "Jane Austen", "year": 1811, "genre": "Romance", "copies": 3},
  { "name": "Middlemarch", "author": "George Eliot", "year": 1871, "genre": "Realist fiction", "copies": 1},
  { "name": "Anna Karenina", "author": "Leo Tolstoy", "year": 1878, "genre": "Realist fiction", "copies": 2},
  { "name": "Madame Bovary", "author": "Gustave Flaubert", "year": 1856, "genre": "Realist fiction", "copies": 2},
  { "name": "Great Expectations", "author": "Charles Dickens", "year": 1861, "genre": "Bildungsroman", "copies": 3},
  { "name": "David Copperfield", "author": "Charles Dickens", "year": 1850, "genre": "Bildungsroman", "copies": 2},
  { "name": "Les Misérables", "author": "Victor Hugo", "year": 1862, "genre": "Historical fiction", "copies": 2},
  { "name": "Crime and Punishment", "author": "Fyodor Dostoevsky", "year": 1866, "genre": "Philosophical fiction", "copies": 2},
  { "name": "The Brothers Karamazov", "author": "Fyodor Dostoevsky", "year": 1880, "genre": "Philosophical fiction", "copies": 1},
  { "name": "The Idiot", "author": "Fyodor Dostoevsky", "year": 1869, "genre": "Psychological fiction", "copies": 1},
  { "name": "War and Peace", "author": "Leo Tolstoy", "year": 1869, "genre": "Historical fiction", "copies": 1},
  { "name": "The Picture of Dorian Gray", "author": "Oscar Wilde", "year": 1890, "genre": "Gothic fiction", "copies": 3},
  { "name": "Dracula", "author": "Bram Stoker", "year": 1897, "genre": "Gothic horror", "copies": 3},
  { "name": "The Strange Case of Dr. Jekyll and Mr. Hyde", "author": "Robert Louis Stevenson", "year": 1886, "genre": "Gothic fiction", "copies": 2},
  { "name": "The Count of Monte Cristo", "author": "Alexandre Dumas", "year": 1844, "genre": "Adventure", "copies": 2},
  { "name": "The Three Musketeers", "author": "Alexandre Dumas", "year": 1844, "genre": "Adventure", "copies": 3},
  { "name": "Don Quixote", "author": "Miguel de Cervantes", "year": 1605, "genre": "Satire", "copies": 1},
  { "name": "The Odyssey", "author": "Homer", "year": -700, "genre": "Epic poetry", "copies": 2},
  { "name": "The Iliad", "author": "Homer", "year": -750, "genre": "Epic poetry", "copies": 2},
  { "name": "The Aeneid", "author": "Virgil", "year": -19, "genre": "Epic poetry", "copies": 1},
  { "name": "The Divine Comedy", "author": "Dante Alighieri", "year": 1320, "genre": "Epic poetry", "copies": 1},
  { "name": "Beowulf", "author": "Unknown", "year": 1000, "genre": "Epic poetry", "copies": 1},
  { "name": "The Canterbury Tales", "author": "Geoffrey Chaucer", "year": 1400, "genre": "Poetry", "copies": 1},
  { "name": "Paradise Lost", "author": "John Milton", "year": 1667, "genre": "Epic poetry", "copies": 1},
  { "name": "Gulliver's Travels", "author": "Jonathan Swift", "year": 1726, "genre": "Satire", "copies": 2},
  { "name": "Robinson Crusoe", "author": "Daniel Defoe", "year": 1719, "genre": "Adventure", "copies": 2},
  { "name": "The Adventures of Tom Sawyer", "author": "Mark Twain", "year": 1876, "genre": "Adventure", "copies": 3},
  { "name": "Adventures of Huckleberry Finn", "author": "Mark Twain", "year": 1884, "genre": "Adventure", "copies": 2},
  { "name": "A Tale of Two Cities", "author": "Charles Dickens", "year": 1859, "genre": "Historical fiction", "copies": 3},
  { "name": "The Grapes of Wrath", "author": "John Steinbeck", "year": 1939, "genre": "Realist fiction", "copies": 2},
  { "name": "East of Eden", "author": "John Steinbeck", "year": 1952, "genre": "Realist fiction", "copies": 2},
  { "name": "Of Mice and Men", "author": "John Steinbeck", "year": 1937, "genre": "Novella", "copies": 4},
  { "name": "The Old Man and the Sea", "author": "Ernest Hemingway", "year": 1952, "genre": "Literary fiction", "copies": 3},
  { "name": "A Farewell to Arms", "author": "Ernest Hemingway", "year": 1929, "genre": "War fiction", "copies": 1},
  { "name": "For Whom the Bell Tolls", "author": "Ernest Hemingway", "year": 1940, "genre": "War fiction", "copies": 1},
  { "name": "The Sun Also Rises", "author": "Ernest Hemingway", "year": 1926, "genre": "Literary fiction", "copies": 2},
  { "name": "Slaughterhouse-Five", "author": "Kurt Vonnegut", "year": 1969, "genre": "Satirical science fiction", "copies": 2},
  { "name": "Catch-22", "author": "Joseph Heller", "year": 1961, "genre": "Satire", "copies": 2},
  { "name": "Beloved", "author": "Toni Morrison", "year": 1987, "genre": "Historical fiction", "copies": 2},
  { "name": "The Bluest Eye", "author": "Toni Morrison", "year": 1970, "genre": "Literary fiction", "copies": 1},
  { "name": "Invisible Man", "author": "Ralph Ellison", "year": 1952, "genre": "Literary fiction", "copies": 1},
  { "name": "Their Eyes Were Watching God", "author": "Zora Neale Hurston", "year": 1937, "genre": "Literary fiction", "copies": 2},
  { "name": "The Color Purple", "author": "Alice Walker", "year": 1982, "genre": "Epistolary novel", "copies": 2},
  { "name": "Things Fall Apart", "author": "Chinua Achebe", "year": 1958, "genre": "Historical fiction", "copies": 3},
  { "name": "The Stranger", "author": "Albert Camus", "year": 1942, "genre": "Philosophical fiction", "copies": 2},
  { "name": "The Plague", "author": "Albert Camus", "year": 1947, "genre": "Philosophical fiction", "copies": 1},
  { "name": "The Metamorphosis", "author": "Franz Kafka", "year": 1915, "genre": "Absurdist fiction", "copies": 3},
  { "name": "The Trial", "author": "Franz Kafka", "year": 1925, "genre": "Absurdist fiction", "copies": 1},
  { "name": "Ulysses", "author": "James Joyce", "year": 1922, "genre": "Modernist", "copies": 1},
  { "name": "Dubliners", "author": "James Joyce", "year": 1914, "genre": "Short stories", "copies": 2},
  { "name": "Mrs Dalloway", "author": "Virginia Woolf", "year": 1925, "genre": "Modernist", "copies": 2},
  { "name": "To the Lighthouse", "author": "Virginia Woolf", "year": 1927, "genre": "Modernist", "copies": 1},
  { "name": "The Sound and the Fury", "author": "William Faulkner", "year": 1929, "genre": "Modernist", "copies": 1},
  { "name": "As I Lay Dying", "author": "William Faulkner", "year": 1930, "genre": "Modernist", "copies": 1},
  { "name": "Heart of Darkness", "author": "Joseph Conrad", "year": 1899, "genre": "Novella", "copies": 2},
  { "name": "The Time Machine", "author": "H. G. Wells", "year": 1895, "genre": "Science fiction", "copies": 3},
  { "name": "The War of the Worlds", "author": "H. G. Wells", "year": 1898, "genre": "Science fiction", "copies": 2},
  { "name": "The Invisible Man", "author": "H. G. Wells", "year": 1897, "genre": "Science fiction", "copies": 2},
  { "name": "A Wrinkle in Time", "author": "Madeleine L'Engle", "year": 1962, "genre": "Science fantasy", "copies": 3},
  { "name": "Dune", "author": "Frank Herbert", "year": 1965, "genre": "Science fiction", "copies": 3},
  { "name": "Foundation", "author": "Isaac Asimov", "year": 1951, "genre": "Science fiction", "copies": 3},
  { "name": "I, Robot", "author": "Isaac Asimov", "year": 1950, "genre": "Science fiction", "copies": 2},
  { "name": "Do Androids Dream of Electric Sheep?", "author": "Philip K. Dick", "year": 1968, "genre": "Science fiction", "copies": 2},
  { "name": "Neuromancer", "author": "William Gibson", "year": 1984, "genre": "Cyberpunk", "copies": 2},
  { "name": "Snow Crash", "author": "Neal Stephenson", "year": 1992, "genre": "Cyberpunk", "copies": 2},
  { "name": "Ender's Game", "author": "Orson Scott Card", "year": 1985, "genre": "Science fiction", "copies": 4},
  { "name": "The Left Hand of Darkness", "author": "Ursula K. Le Guin", "year": 1969, "genre": "Science fiction", "copies": 2},
  { "name": "A Wizard of Earthsea", "author": "Ursula K. Le Guin", "year": 1968, "genre": "Fantasy", "copies": 3},
  { "name": "The Lion, the Witch and the Wardrobe", "author": "C. S. Lewis", "year": 1950, "genre": "Fantasy", "copies": 5},
  { "name": "The Fellowship of the Ring", "author": "J. R. R. Tolkien", "year": 1954, "genre": "Fantasy", "copies": 3},
  { "name": "The Two Towers", "author": "J. R. R. Tolkien", "year": 1954, "genre": "Fantasy", "copies": 3},
  { "name": "The Return of the King", "author": "J. R. R. Tolkien", "year": 1955, "genre": "Fantasy", "copies": 3},
  { "name": "The Silmarillion", "author": "J. R. R. Tolkien", "year": 1977, "genre": "Fantasy", "copies": 2},
  { "name": "Harry Potter and the Sorcerer's Stone", "author": "J. K. Rowling", "year": 1997, "genre": "Fantasy", "copies": 6},
  { "name": "The Golden Compass", "author": "Philip Pullman", "year": 1995, "genre": "Fantasy", "copies": 3},
  { "name": "The Once and Future King", "author": "T. H. White", "year": 1958, "genre": "Fantasy", "copies": 2},
  { "name": "The Princess Bride", "author": "William Goldman", "year": 1973, "genre": "Fantasy", "copies": 2}
]